FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    dbt-core==1.9.0 \
    dbt-postgres==1.9.0 

WORKDIR /usr/app/dbt
COPY entrypoint_dbt.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint_dbt.sh

EXPOSE 8001
ENTRYPOINT ["/usr/local/bin/entrypoint_dbt.sh"]