FROM apache/airflow:3.1.3

# Copy requirements as root first
USER root
COPY requirements-airflow.txt /tmp/requirements-airflow.txt
RUN chown airflow:root /tmp/requirements-airflow.txt

# Switch to airflow user and install
USER airflow
RUN pip install --no-cache-dir -r /tmp/requirements-airflow.txt && rm /tmp/requirements-airflow.txt